# Generated by Django 5.2.4 on 2025-08-06 09:20

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=documents.models.original_document_path)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('encryption_key', models.CharField(blank=True, max_length=256, null=True)),
                ('is_redacted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedactedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redacted_file', models.FileField(upload_to=documents.models.redacted_document_path)),
                ('redacted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redacted_version', to='documents.document')),
                ('redacted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redactions_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redacted_at'],
            },
        ),
    ]
