# Generated by Django 5.2.4 on 2025-08-11 08:38

import django.db.models.deletion
import redaction.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedactionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_file', models.FileField(upload_to=redaction.models.redaction_orig_path)),
                ('redacted_file', models.FileField(blank=True, null=True, upload_to=redaction.models.redaction_out_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedactionRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=128)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='redaction.redactiontask')),
            ],
        ),
    ]
